include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    directives_ordering: false
    avoid_positional_boolean_parameters: false