name: flutter_ui_test_demo
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  url_launcher: ^6.3.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_annotation: ^4.9.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

scripts:
  generate-code: flutter pub run build_runner watch --delete-conflicting-outputs
  generate-code-one: flutter pub run build_runner build --delete-conflicting-outputs
  run-android-ui-test: ./ui_test/run_android_ui_test.sh
  run-ios-ui-test: ./ui_test/run_ios_ui_test.sh
  run-ui-test: ./run_ui_test.sh